### ISSUE TITLE
need support assets config

### ISSUE THREAD

**Issue by Jimmysh** [samatechtw/nx-vue3-vite#40]
https://github.com/nrwl/nx/blob/master/packages/web/src/executors/webpack/schema.json#L73

**Comment by samatechtw** [comment]
Yes, that's something the plugin should support. We use a different asset strategy for our internal projects, so it might be a while before I have time for this. Contributions are welcom!

**Comment by samatechtw** [comment]
@Jimmysh Actually, can you explain what you're looking for in more detail? Assets work fine in our internal apps, and the above link is broken (maybe due to recent Nx rollup support?).

If this is about webpack asset config, this plugin doesn't support webpack. For everything else, you should be able to modify `vite.config.ts`

**Comment by Jimmysh** [comment]
It can copy assets what your want. Example I can copy some icons at runtime, but these icons will not be saved in your project. I still be package in prod.

**Comment by abemscac** [comment]
Hi @sampullman 

It seems that `assets` is one of the option in the [NX webpack executor](https://nx.dev/packages/web/executors/webpack#options).
I created a new app with webpack as bundler to see how it actually works, and here's what I've observed:

1. `assets` is an array. Elements can either be a string or [an object](https://nx.dev/packages/web/executors/webpack?ref=root/properties/assets/items/oneOf/0) (they can both show up at the same time):
  - If it's a string, it must start with the `src` folder of the app, such as `apps/my-app/src/**/*`.
    - For example, if I put `apps/my-app/src/favicon.ico` in `assets`, the `favicon.ico` will then be served at `localhost:4200/favicon.ico`.
  - If it's an object, targeted files will be served at the `output` we specified in the object. This can be used to include assets in `libs` folder, or even outside of the repository (if we have enough permission).
    - For example,`{ "glob": "**/*", "input": "libs/assets/", "output": "./assets" }` will serve all of the files in `libs/assets` at `localhost:4200/assets`.
    - Another example is `{ "glob": "**/*", "input": "/Users/user/Desktop/", "output": "./desktop" }`, which will serve all of the files in `/Users/user/Desktop/` at `localhost:4200/desktop`.
2. We can have different `assets` setup for different environment (development, production, etc). Specified assets will be included in the build output.

I think maybe the same functionality can be achieved by tuning specific property(s) in `vite.config.ts`? I'm not really sure. :thinking:

**Comment by sampullman** [comment]
Vite has some basic configuration options for asset handling, like `assetsDir`, `assetsInlineLimit`, `publicDir`, `assetsInclude`, etc. But I don't see anything that exactly matches the webpack behavior you describe.

@Jimmysh I think it's possible to implement with a Vite plugin, but would be outside the scope of this project unless it was implemented in Vite itself.

@abemscac Thanks for looking into it! I'm going to close this, because I think it's too complicated to implement and maintain our own solution.
